### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=action

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM users", // ignora el SQL Injection
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Actualizar una película parcialmente con PATCH
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "title": "Sueños de libertad",
    "year": 1994
}

### Actualizar o crear una película con PUT
PUT http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "director": "F. Darabont"
}




### Principales diferencias de POST, PUT y PATCH

#### POST: Crear un recurso en el servidor.
##### URL: /movies
##### No es idempotente.

#### PUT: Crear (si no existe) o reemplazar un recurso en el servidor.
##### URL: /movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
##### Es idempotente: el recurso siempre será el mismo.

#### PATCH: Actualizar parcialmente un recurso en el servidor.
##### URL: /movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
##### Es idempotente: el recurso siempre será el mismo. Pero depende de la implementación del servidor.
